core/urls.py
from django.urls import path

from core import views , transfer , transaction , payment_request , credit_card 
from .views import HomeView , contatct_us , need_help , about_us , create_notification , api_buttons
from .api import CreditCardDetailAPIView , FundCreditCardAPIView , WithdrawCreditCardAPIView , DeleteCreditCardAPIView , SearchUsersRequestAPIView , AmountRequestAPIView , AmountRequestProcessAPIView , AmountRequestConfirmationAPIView , AmountRequestFinalProcessAPIView , AmountRequestCompletedAPIView , SettlementConfirmationAPIView , SettlementProcessingAPIView , SettlementCompletedAPIView , DeletePaymentRequestAPIView , TransactionListAPIView , TransactionDetailAPIView , SearchUsersAccountNumberAPIView , AmountTransferAPIView , AmountTransferProcessAPIView , TransferConfirmationAPIView , TransferFinalProcessAPIView , TransferCompletedAPIView , HomeAPIView , ContactUsAPIView , NeedHelpAPIView , AboutUsAPIView

app_name = 'core'


urlpatterns = [
    #core
    path('', HomeView.as_view(), name='home'),
    path('contatct',contatct_us, name='contatct_us'),
    path('faq',need_help, name='faq'),
    path('about-us',about_us, name='about_us'),
    path('create-notification/', create_notification, name='create_notification'),
    path('create-notification/', create_notification, name='create_notification'),
    path('api-buttons/', api_buttons, name='api-buttons'),

    # transfer
    path('search-account/', transfer.search_users_account_number, name='search-account'),
    path('amount-transfer/<account_number>/', transfer.amount_transfer, name='amount-transfer'),
    path('amount-transfer-process/<account_number>/', transfer.amount_transfer_process, name='amount-transfer-process'),
    path('transfer-confirmation/<account_number>/<transaction_id>/', transfer.transfer_confirmation, name='transfer-confirmation'),
    path('transfer-process/<account_number>/<transaction_id>/', transfer.transfer_process, name='transfer-process'),
    path('transfer-completed/<account_number>/<transaction_id>/', transfer.transfer_completed, name='transfer-completed'),
    
    # transaction
    path('transactions/', transaction.transaction_lists, name='transactions'),
    path('transactions-detail/<transaction_id>/', transaction.transaction_detail, name='transaction-detail'),
    
    # payment request
    path('request-search-account/', payment_request.search_users_request, name='request-search-account'),
    path('amount-request/<account_number>/', payment_request.amount_request, name='amount-request'),
    path('amount-request-process/<account_number>/', payment_request.amount_request_process, name='amount-request-process'),
    path('amount-request-confirmation/<account_number>/<transaction_id>/', payment_request.amount_request_confirmation, name='amount-request-confirmation'),
    path('amount-request-final-process/<account_number>/<transaction_id>/', payment_request.amount_request_final_process, name='amount-request-final-process'),
    path('amount-request-completed/<account_number>/<transaction_id>/', payment_request.request_completed, name='amount-request-completed'),

    # request Settled
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settlement_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),
    path("delete-request/<account_number>/<transaction_id>/", payment_request.delete_payment_request, name="delete-request"),

    # credit card
    path('card/<card_id>/', credit_card.card_detail, name='card-detail'),
    path("fund-credit-card/<card_id>/", credit_card.fund_credit_card, name="fund-credit-card"),
    path("withdraw_fund/<card_id>/", credit_card.withdraw_fund, name="withdraw_fund"),
    path("delete_card/<card_id>/", credit_card.delete_card, name="delete_card"),

    # api credite card
    path("api/credit-cards/<str:card_id>/", CreditCardDetailAPIView.as_view(), name="credit-card-detail-api"),
    path("api/credit-cards/fund/<str:card_id>/", FundCreditCardAPIView.as_view(), name="fund-credit-card-api"),
    path("api/credit-cards/withdraw/<str:card_id>/", WithdrawCreditCardAPIView.as_view(), name="withdraw-credit-card-api"),
    path("api/credit-cards/delete/<str:card_id>/", DeleteCreditCardAPIView.as_view(), name="delete-credit-card-api"),

    # payment requist
    path("api/search-users/", SearchUsersRequestAPIView.as_view(), name="search-users-request-api"),
    path("api/amount-request/<str:account_number>/", AmountRequestAPIView.as_view(), name="amount-request-api"),
    path("api/amount-request/process/<str:account_number>/", AmountRequestProcessAPIView.as_view(), name="amount-request-process-api"),
    path("api/amount-request/confirmation/<str:account_number>/<str:transaction_id>/", AmountRequestConfirmationAPIView.as_view(), name="amount-request-confirmation-api"),
    path("api/amount-request/final/<str:account_number>/<str:transaction_id>/", AmountRequestFinalProcessAPIView.as_view(), name="amount-request-final-api"),
    path("api/amount-request/completed/<str:account_number>/<str:transaction_id>/", AmountRequestCompletedAPIView.as_view(), name="amount-request-completed-api"),
    # >>>>>>>>>>>>>>>Settled API<<<<<<<<<<<<<<<<<<<< #
    path("api/settlement-confirmation/<str:account_number>/<str:transaction_id>/", SettlementConfirmationAPIView.as_view(), name="settlement-confirmation-api"),
    path("api/settlement-process/<str:account_number>/<str:transaction_id>/", SettlementProcessingAPIView.as_view(), name="settlement-process-api"),
    path("api/settlement-completed/<str:account_number>/<str:transaction_id>/", SettlementCompletedAPIView.as_view(), name="settlement-completed-api"),
    path("api/delete-payment-request/<str:account_number>/<str:transaction_id>/", DeletePaymentRequestAPIView.as_view(), name="delete-payment-request-api"),

    # transaction api
    path("api/transactions/", TransactionListAPIView.as_view(), name="transactions-api"),
    path("api/transactions/<str:transaction_id>/", TransactionDetailAPIView.as_view(), name="transactions-detail-api"),

    # transfer
    path("api/search-users/", SearchUsersAccountNumberAPIView.as_view(), name="search-users-account-numbe-api"),
    path("api/amount-transfer/<str:account_number>/", AmountTransferAPIView.as_view(), name="amount-transfer-api"),
    path("api/amount-transfer-process/<str:account_number>/", AmountTransferProcessAPIView.as_view(), name="amount-transfer-process-api"),
    path("api/transfer-confirmation/<str:account_number>/<str:transaction_id>/", TransferConfirmationAPIView.as_view(), name="transfer-confirmation-api"),
    path("api/transfer-final/<str:account_number>/<str:transaction_id>/", TransferFinalProcessAPIView.as_view(), name="transfer-final-api"),
    path("api/transfer-completed/<str:account_number>/<str:transaction_id>/", TransferCompletedAPIView.as_view(), name="transfer-completed-api"),

    # home api & contact us api & need help api & about us api
    path("api/", HomeAPIView.as_view(), name="home-api"),
    path("api/contact-us/", ContactUsAPIView.as_view(), name="contact-us-api"),
    path("api/need-help/", NeedHelpAPIView.as_view(), name="need-help-api"),
    path("api/about-us/", AboutUsAPIView.as_view(), name="about-us-api"),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('userauths.urls')),
    path('', include('core.urls')),
    path('account/', include('account.urls')),

    # Translation url
    path('i18n/', include('django.conf.urls.i18n')),
    # rosetta translation
    path('rosetta/', include('rosetta.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms


from core.models import CreditCard


class CreditCardForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Card Holder Name"}))
    number = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Card Number"}))
    month = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Expiry Month"}))
    year = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"Expiry Month"}))
    cvv = forms.IntegerField(widget=forms.NumberInput(attrs={"placeholder":"CVV"}))

    class Meta:
        model = CreditCard
        fields = ['name', 'number', 'month', 'year', 'cvv', 'card_type']

core/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse


from account.models import Account
from userauths.models import User
from .models import Home , Notification
from core.models import CreditCard

# Create your views here.


class HomeView(DetailView):
    model = Home
    template_name = 'core/home.html'
    context_object_name = 'home'

    def get_object(self):
        return Home.objects.first()




def contatct_us(request):
    return render(request,'core/contact.html')


def need_help(request):
    return render(request, 'core/need_help.html')


def about_us(request):
    return render(request, 'core/about-us.html')



@login_required
def create_notification(request):
    receiver_id = request.POST.get('receiver_id')
    amount = request.POST.get('amount')
    notification_type = request.POST.get('notification_type', 'Credit Alert')

    receiver_user = get_object_or_404(User, id=receiver_id)
    sender_account = get_object_or_404(Account, user=request.user)

    notif = Notification.objects.create(
        user=receiver_user,
        sender=sender_account,
        notification_type=notification_type,
        amount=amount
    )

    return JsonResponse({
        "status": "success",
        "sender_name": notif.sender_full_name,
        "sender_image": notif.sender_image_url or "",
        "amount": notif.amount,
        "notification_type": notif.notification_type
    })


def api_buttons(request):
    cards = CreditCard.objects.filter(user=request.user)
    return render(request, "core/api.html", {'cards': cards})

core/templates/transfer/amount_transfer.html
{% extends "auth_base.html" %}
{% load static %}
{% load humanize %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>{% translate "Make a Payment" %}</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">{% translate "Step 2 of 3" %}</span>
                            <h5>{% translate "Set Amount of transfer" %}</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                    <!-- <img src="{{ account.user.kyc.image.url }}" alt="image"> -->
                                    <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">

                                </div>
                                <div class="text-area">
                                    <p>{{ account.user.kyc.full_name|title }}</p>
                                    <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                    <span class="mdr">{{ account.user.email }}</span>
                                </div>
                                </div>
                                <div class="right">
                                    
                                    <a href="{% url 'core:search-account' %}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action="{% url 'core:amount-transfer-process' account.account_number %}" method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">{% translate "You Send" %}</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="{{ request.user.account.account_balance|intcomma }}" type="number" name='amount_send' id="amount_send">
                            </div>
                            <p>{% translate "Available Balance" %}<b>${{ request.user.account.account_balance|intcomma }}</b></p>
                            <b id="new_balance"></b>
                            <b class="text-danger" id="error-div"></b>
                        </div>


                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">{% translate "Payment Description" %}</span>
                            <div class="input-area">
                                <input class="xxlr" onkeyup="CalculateBalance()" placeholder="{% translate 'Payment for fees' %}" type="text" name="description">
                                
                            </div>
                        </div>

                        <!-- js -->
                        <script>
                            function CalculateBalance(){
                                let available_balance = "{{ request.user.account.account_balance }}" // get user account balance
                                let new_balance = document.getElementById("new_balance")
                                let sendAmount_input = document.getElementById("amount_send")
                                let sendAmount = sendAmount_input.value
                                let errorDive = document.getElementById("error-div")
                                let total_to_pay = document.getElementById("total-to-pay")

                                let errors = []

                                new_bal = available_balance - sendAmount
                                console.log(new_bal);

                                // new_balance.innerHTML = `New Balance $${new_bal.toString().replace(/\B(?))}`;
                                new_balance.innerHTML = `<b style='font-size: 18px; font-weight: 400; color: var(--para-color);'>{% translate "New Balance" %}</b> <b style='font-size: 18px; font-weight: 500;'> $${new_bal.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;
                                total_to_pay.innerHTML = `USD <b> $${sendAmount.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;

                                if (new_bal < 0){
                                    new_balance.style.color = "red"
                                    alert("You can only send $" + available_balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","))
                                } else {
                                    new_balance.style.color = "#27276e"

                                }
                            }
                        </script>
                        <ul class="total-fees">
                            
                        </ul>
                        <ul class="total-fees pay">
                            <li>
                                <h5>{% translate "Total To Pay" %}</h5>
                            </li>
                            <li>
                                <h5 id="total-to-pay">$ 0.00</h5>
                            </li>
                        </ul>
                        <div class="footer-area mt-40">
                            <a href="pay-step-1.html">{% translate "Previous Step" %}</a>
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff;" class="active">{% translate "Next" %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
{% endblock content %}

core/templates/transfer/transfer-completed.html
{% extends "auth_base.html" %}
{% load static %}
{% load humanize %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>{% translate "Make a Payment" %}</h4>
                        <div class="icon-area">
                            <!-- <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon"> -->
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>{% translate "Money Sent" %}</h3>
                            <p>{% translate "Payment of" %} <b>${{transaction.amount}}</b> {% translate "was sent to" %} <b>{{account.user.kyc.full_name}}</b></p>
                            <h5><a href=""><b>{% translate "View Detail" %}</b></a> | <a href=""><b>{% translate "Send Another Payment" %}</b></a></h5>
                        </div>
                        <!-- <div class="share-link">
                            <p>Share direct link with your  payer</p>
                            <ul class="d-flex align-items-center justify-content-center">
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/whatsapp.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/skype.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/messenger.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/copy-link.png' %}" alt="icon"></a>
                                </li>
                            </ul>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
{% endblock content %}

core/templates/transfer/transfer-confirmation.html
{% extends "auth_base.html" %}
{% load static %}
{% load humanize %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>{% translate "Make a Payment" %}</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">{% translate "Step 3 of 3" %}</span>
                            <h5>{% translate "Confirm Your Transfer" %}</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                    <!-- <img src="{{ account.user.kyc.image.url }}" alt="image"> -->
                                    <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"  alt="image">

                                </div>
                                <div class="text-area">
                                    <p>{{ account.user.kyc.full_name|title }}</p>
                                    <span class="mdr"><b>{{ account.account_number }}</b></span> <br>
                                    <span class="mdr">{{ account.user.email }}</span>
                                </div>
                                </div>
                                <div class="right">
                                    
                                    <a href="{% url 'core:search-account' %}">
                                        <i class="icon-h-edit"></i>
                                        {% translate "Edit" %}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>{% translate "Payment Details" %}</h6>
                            <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    {% translate "Edit" %}
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>{% translate "You Send" %}</span>
                                        <b>{{ transaction.amount }} $</b>
                                    </li>
                                    <li>
                                        <span>{% translate "Recipient gets" %}</span>
                                        <b>{{ transaction.amount }} $</b>
                                    </li>
                                    <li>
                                        <span>{% translate "E-mail of receiver" %}</span>
                                        <b>{{ account.user.email }}</b>
                                    </li>
                                    <!-- <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li> -->
                                    <li>
                                        <span>{% translate "Description" %}</span>
                                        <b>{{ transaction.description }}</b>
                                    </li>
                                    <li>
                                        <span>{% translate "Transfer was initated on" %} </span>
                                        <b>{{ transaction.date }}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">{% translate "I confirm the payment details above" %}</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="pay-step-2.html">{% translate "Previous Step" %}</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">{% translate "Pay" %}</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">{% translate "transfer" %}</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">{% translate "Confirm" %}</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <!-- <i class="icon-a-left-arrow"></i> -->
                                                <!-- {% translate "Back" %} -->
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>{% translate "Confirm Transfer" %}!</h4>
                                            <p>{% translate "Enter PIN Number" %}</p>
                                            <form action="{% url 'core:transfer-process' account.account_number transaction.transaction_id  %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength='4' maxlength='4' name='pin-number' type="text">
                                                    
                                                </div>
                                                <button type='submit' class="mt-60 confirm">{% translate "Confirm" %}</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                                            <h3>{% translate "Success" %}</h3>
                                            <p>{% translate "Transfer was completed" %}.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->
{% endblock content %}